name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --output-path=dist/coreui-free-angular-admin-template --base-href /my-angular-project/

      - name: List output directory
        run: ls -alh dist/coreui-free-angular-admin-template

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/coreui-free-angular-admin-template

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
